# Generated by Django 3.2 on 2023-09-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0009_auto_20230224_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.FileField(upload_to='attachments/1402/6', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='request',
            name='number',
            field=models.CharField(default='167978', max_length=6, verbose_name='شماره درخواست'),
        ),
    ]
